version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: iluvcoffee-db
  test-db:
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
  mongo-db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
       MONGODB_DATABASE: iluvcoffee-db
